### ISSUE TITLE
Typos and example page layout issues

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/libHelper#12]
<img width="1145" alt="Screen shot 2019-08-18 at 16 03 38" src="https://user-images.githubusercontent.com/49612/63226506-2506b400-c1d2-11e9-8b99-3fc7fcb970a1.png">

**Comment by otzbergnet** [comment]
Thank you for these reports - made some quick changes this morning to improve these. Need to figure out why GitHub doesn't send me any eMails about these issues ;)
