### ISSUE TITLE
Support for 10.13.x

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/libHelper#4]
Safari 11 and 12 on macOS 10.13.x can use Safari Extension Apps.

I'd appreciate a compatible build of your app. Thanks!

**Comment by gingerbeardman** [comment]
I still think this would be good, but I just upgraded to Mojave

**Comment by otzbergnet** [comment]
I agree that this would be neat, but I must admit that I don't have a machine running 10.13.x available :( I'll need to visit my mom and see if she's still on an old version (I doubt it, I always tell her to update)... So no promises...

**Comment by gingerbeardman** [comment]
Well, I think building targeting 10.13 would be enough. Xcode would warn of any API issues, and you can offer 10.13 compatibility "unsupported"?

**Comment by otzbergnet** [comment]
Alright, I am convinced, I set the deployment target to 10.13 :)

**Comment by gingerbeardman** [comment]
Another extension that takes this approach is 

https://github.com/yimingliu/reverse-image-search-safari

**Comment by otzbergnet** [comment]
Version 1.8.1 has been submitted to Apple #11 - closing for now, hoping the changes are the desired enhancement
