### ISSUE TITLE
Toolbar icon badge is not persistent

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/libHelper#5]
Firstly, thanks for this great tool! I have been coming up against scientific paper paywalls and thought there had to be a better way. Happy to find that there is!

I notice that when a match is found, there are two things that happen:

1. Page gets a badge
   - persistent, when I go to view other pages/tabs and come back it is still there
2. Safari toolbar icon gets a badge
   - not persistent, when I go to view other pages/tabs and come back it is gone

I feel that the toolbar icon should be persistent. 

It will probably need to be re-validated when the current tab is changed.

**Comment by otzbergnet** [comment]
This is indeed a bug that I have been pushing off for a while - as I wasn't sure I was a fan of the toolbar badge. Safari sadly limits the ability of the dev. in Chrome you can change the color of the icon, which makes it a lot more obvious. One of my thoughts is to actually remove the badge entirely as it adds relatively little value.

Appreciate the thought though!

**Comment by gingerbeardman** [comment]
I would choose the path of least resistance.

My feeling is that this would be to add a small amount of code to revalidate the toolbar badge icon when a tab is changed.

**Comment by otzbergnet** [comment]
Appreciate your kind guidance and suggestion.

I took your feedback as a sign, that I should fix this now rather than later... I've got this working in dev right now and will close the issue, once this releases

**Comment by gingerbeardman** [comment]
Awesome! Thanks in advance.

**Comment by otzbergnet** [comment]
Version 1.8 has been submitted to Apple #10 - I tested the persistence and quite like it myself. Still room for improvement though ;)
