### ISSUE TITLE
Page badge is not obvious to "first-time" or "inexperienced" users

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/libHelper#6]
I notice that when a match is found, there are two things that happen:

1. Page gets a badge
2. Safari toolbar icon gets a badge

Given the problem with the safari toolbar badge #5, and - as a first time user - my lack of knowledge of how the badges from this extension present themselves, I missed the badge in the page. 🤦‍♂️

Thoughts are that the position is slightly odd, 1/3 down the page on the right side. But perhaps the real issue is that I was unaware it was added by the extension. Maybe I have not yet sene enough scientific paper portals!

Some proposed solutions:
- animate the badge as it is added to draw attention to it
- enhance app welcome message to educate new users of what to expect

Thanks again!

**Comment by otzbergnet** [comment]
the placement of the badge was taken as an inspiration from unpaywall.org Chrome Extension, the folk that provide one of the two (soon three) APIs I am using to power the app. 

I think I'll work on the "enhance app welcome message to educate new users of what to expect". For users coming through the App Store they will hopefully have seen screenshots. For users coming through my web-site the same is true, but it still seems a solid idea to puruse

**Comment by gingerbeardman** [comment]
I think the app doe s good job so far, but it stops short of setting expectations of what the browser will show.

- a page opened in Safari on first launch?
  - could be "lorem ipsum" page showing the badge
- a slideshow of images in the app?

**Comment by otzbergnet** [comment]
The next version will have a "Show me an example" button, to help users shape their own expectations.

I wanted to avoid the intrusion of a page automatically opening, even though that would have probably gotten the most attention.

I really appreciate the thought you have given here and the kind suggestion

**Comment by gingerbeardman** [comment]
My pleasure! Thanks for being so receptive.

**Comment by otzbergnet** [comment]
Version 1.8 has been submitted to Apple #10 - closing for now, hoping the changes are the desired enhancement
