### ISSUE TITLE
Context menus do not function for me

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/libHelper#9]
I cannot actually get these context menus to do anything.

Also, perhaps they should only appear when some text is selected/highlighted?

**Comment by otzbergnet** [comment]
The context menu should have two states:

If nothing is selected they turn into a "visit xzy" 

![Bildschirmfoto 2019-08-10 um 07 42 51](https://user-images.githubusercontent.com/43129918/62818105-87acdf80-bb42-11e9-844f-52a26519a6ed.png)

If something is selected they indicate what was selected:

![Bildschirmfoto 2019-08-10 um 07 42 58](https://user-images.githubusercontent.com/43129918/62818110-96939200-bb42-11e9-8256-617d1ee60f9f.png)

If this is not happening for you, please provide a little extra detail on your OS / Safari version. Many thanks!

**Comment by otzbergnet** [comment]
I obviously realized that my localization has a bug :)

**Comment by gingerbeardman** [comment]
OK, it works as intended just now for me. I will close this.

Extensions stop working from time to time with my install. Not sure why! But a restart of Safari gets things going again.

**Comment by otzbergnet** [comment]
Out of curiosity, do you run the AppStore version or did you run from XCode? The reason I am asking is that the version here is missing a .plist file that contains the API Key for core.ac.uk and soon Open Access Button. With the file not being there - and I feel terrible for the nonexistent handling for that condition - the app is bound to crash and being unable to recover.

Just curious about the statement of the app stopping to work...

**Comment by gingerbeardman** [comment]
I use the Mac App Store version.
